// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiDmsQY-VrVPZZnatfC8Hb8DuT0kNjGBs',
    appId: '1:661445274435:web:9c32c57773e4acb9dfddf6',
    messagingSenderId: '661445274435',
    projectId: 'fir-for-flutter-9220f',
    authDomain: 'fir-for-flutter-9220f.firebaseapp.com',
    storageBucket: 'fir-for-flutter-9220f.appspot.com',
    measurementId: 'G-TJE3PY8CVH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABlSt9UvCnJNp8ibYjglL11ZKZAavBjNw',
    appId: '1:661445274435:android:f87786437e65148bdfddf6',
    messagingSenderId: '661445274435',
    projectId: 'fir-for-flutter-9220f',
    storageBucket: 'fir-for-flutter-9220f.appspot.com',
  );
}
